name: Delete Single Resource

on:
  workflow_dispatch:
    inputs:
      storageName:
        description: 'Enter Storage Account Name'
        required: true

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete Storage Account
      run: |
        az storage account delete \
          --name ${{ github.event.inputs.storageName }} \
          --resource-group rg-bicep-demo \
          --yes